### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by weifan-zhao** [shibing624/pytextclassifier#10]
<img width="528" alt="截屏2023-07-07 11 08 04" src="https://github.com/shibing624/pytextclassifier/assets/48010074/10c75b4f-8e43-4567-b3d0-1c07c768d658">

**Comment by shibing624** [comment]
check your torch installed correct.  pytextclassifier use the torch lib, check :`python -c "import torch"`

**Comment by weifan-zhao** [comment]
<img width="424" alt="截屏2023-07-07 13 48 26" src="https://github.com/shibing624/pytextclassifier/assets/48010074/d21ff59b-67da-436b-ba01-24726a7837f0">

**Comment by shibing624** [comment]
我测试没问题，python -c "import pytextclassifier"   pytextclassifier-1.3.6
