### ISSUE TITLE
pytextclassifier  运行出错

### ISSUE THREAD

**Issue by lgjut** [shibing624/pytextclassifier#19]
`

# -*- coding: utf-8 -*-
"""
@author:XuMing(xuming624@qq.com)
@description: 
"""
import sys

sys.path.append('..')
from pytextclassifier import TextCNNClassifier

if __name__ == '__main__':
    m = TextCNNClassifier(output_dir='models/textcnn-toy')
    data = [
        ('高血压', '高血压30余年'),
        ('高血压', '咽痛3天 咽痛3天，咽红肿痛'),
        ('糖尿病', '糖尿病，高血压多年'),
        ('糖尿病', '糖尿病，高血压多年'),
        ('糖尿病', '该患者上周与朋友聚会吃了些甜食后，出现饥饿口干乏力，故来医院就诊')
    ]
    # train and save best model
    m.train(data, num_epochs=9, evaluate_during_training_steps=1)
    print(m)
    # load best model from model_dir
    m.load_model()
    #predict_label, predict_proba = m.predict(['福建春季公务员考试报名18日截止 2月6日考试',
    #                                          '意甲首轮补赛交战记录:米兰客场8战不败国米10年连胜'])
    #print(f'predict_label: {predict_label}, predict_proba: {predict_proba}')

    test_data = [
        ('高血压', '高血压2年 头晕'),
        ('高血压', '高血压2年 头晕'),
    ]
    acc_score = m.evaluate_model(test_data)
    print(f'acc_score: {acc_score}')  # 1.0

`

出错信息：

TypeError: an integer is required (got type NoneType)

**Comment by shibing624** [comment]
跑示例代码，看下是否ok。

改代码后，需要自己debug下。
