### ISSUE TITLE
使用用例更换模型名称报错

### ISSUE THREAD

**Issue by stay-leave** [shibing624/pytextclassifier#8]
大佬您好！我将中文文本分类的示例的模型名称改为了textrnn_att，但是却报错找不到文件。请问需要怎么调用模型？
![Uploading image.png…]()

**Comment by shibing624** [comment]
不是改名的问题，深度模型需要调用对应的方法`from pytextclassifier import TextRNNClassifier`，参考：https://github.com/shibing624/pytextclassifier/blob/master/examples/textrnn_classification_demo.py

**Comment by stay-leave** [comment]
原来是这样，懂了，谢谢大佬
