### ISSUE TITLE
减小inference时候的list size

### ISSUE THREAD

**Issue by flydsc** [shibing624/pytextclassifier#9]
Hello，
感谢提供很好的工具

想请教一下在使用的时候，例如fasttext的模型，在使用model.predict的时候是传入一个list，如果list过大，遇到了报错的情况。

我们是否有一个参数可以设计batch来做推理？

**Comment by shibing624** [comment]
predict处理的时候默认已经分batch处理了，如果报错，可以改小fasttext的batch_size=8, 默认是64。或者enable_ngram=False关闭ngram特征。
